// Code generated by acceptance-pipeline. Stubs are regenerated; bound implementations are preserved.
// Source: specs/US06-rename-node.txt

package acceptance_test

import (
	"strings"
	"testing"
)

// Author renames a node.
// Source: specs/US06-rename-node.txt:2
func Test_Author_renames_a_node(t *testing.T) {
	// GIVEN an outline with a node titled "Chapter One".
	dir := initProject(t)
	r := addNodeJSON(t, dir, "Chapter One")
	mp := getNodeMP(t, r)
	sid := getNodeSID(t, r)

	// WHEN the author renames it to "The Beginning".
	runLmkSuccess(t, dir, "rename", mp, "The Beginning")

	// THEN the node's title becomes "The Beginning".
	// (Reflected as slug "the-beginning" in list output)

	// THEN all filenames for the node reflect the new slugified title.
	files := listMDFiles(t, dir)
	foundNewSlug := false
	for _, f := range files {
		if strings.Contains(f, "the-beginning") {
			foundNewSlug = true
		}
		if strings.Contains(f, "chapter-one") {
			t.Fatalf("old slug still present in filename: %s", f)
		}
	}
	if !foundNewSlug {
		t.Fatal("expected filename with new slug 'the-beginning'")
	}

	// THEN the node's stable identifier is unchanged.
	result := listJSON(t, dir)
	allNodes := flattenNodes(getNodes(t, result))
	found := false
	for _, n := range allNodes {
		if n["sid"].(string) == sid {
			found = true
			// THEN the node's position in the outline is unchanged.
			if n["mp"].(string) != mp {
				t.Fatalf("expected MP %s unchanged, got %s", mp, n["mp"])
			}
		}
	}
	if !found {
		t.Fatalf("SID %s not found after rename", sid)
	}
}

// Renaming updates the canonical title in the draft.
// Source: specs/US06-rename-node.txt:15
func Test_Renaming_updates_the_canonical_title_in_the_draft(t *testing.T) {
	// GIVEN a node titled "Old Title".
	dir := initProject(t)
	r := addNodeJSON(t, dir, "Old Title")
	mp := getNodeMP(t, r)
	sid := getNodeSID(t, r)

	// WHEN the author renames it to "New Title".
	runLmkSuccess(t, dir, "rename", mp, "New Title")

	// THEN the draft document's stored title reads "New Title".
	draftFile := mp + "_" + sid + "_draft_new-title.md"
	content := readFile(t, dir, draftFile)
	if !strings.Contains(content, "title: New Title") {
		t.Fatalf("expected 'title: New Title' in draft, got:\n%s", content)
	}
}
