// Code generated by acceptance-pipeline. Stubs are regenerated; bound implementations are preserved.
// Source: specs/US07-manage-document-types.txt

package acceptance_test

import (
	"strings"
	"testing"
)

// Author lists document types for a node.
// Source: specs/US07-manage-document-types.txt:2
func Test_Author_lists_document_types_for_a_node(t *testing.T) {
	// GIVEN a node with a draft and notes document.
	dir := initProject(t)
	r := addNodeJSON(t, dir, "Test Node")
	mp := getNodeMP(t, r)

	// WHEN the author lists types for that node.
	stdout := runLmkSuccess(t, dir, "types", "list", mp)

	// THEN "draft" and "notes" are displayed.
	if !strings.Contains(stdout, "draft") {
		t.Fatalf("expected 'draft' in types output: %s", stdout)
	}
	if !strings.Contains(stdout, "notes") {
		t.Fatalf("expected 'notes' in types output: %s", stdout)
	}
}

// Author adds a custom document type.
// Source: specs/US07-manage-document-types.txt:12
func Test_Author_adds_a_custom_document_type(t *testing.T) {
	// GIVEN a node with draft and notes documents.
	dir := initProject(t)
	r := addNodeJSON(t, dir, "Test Node")
	mp := getNodeMP(t, r)

	// WHEN the author adds a "characters" document type to the node.
	runLmkSuccess(t, dir, "types", "add", "characters", mp)

	// THEN the node has 3 document types: draft, notes, and characters.
	stdout := runLmkSuccess(t, dir, "types", "list", mp)
	for _, expected := range []string{"draft", "notes", "characters"} {
		if !strings.Contains(stdout, expected) {
			t.Fatalf("expected %q in types output: %s", expected, stdout)
		}
	}

	// THEN a new empty file of type "characters" is created.
	sid := getNodeSID(t, r)
	expectedFile := mp + "_" + sid + "_characters.md"
	if !fileExists(dir, expectedFile) {
		t.Fatalf("expected characters file %s to exist", expectedFile)
	}
}

// Author removes a custom document type.
// Source: specs/US07-manage-document-types.txt:23
func Test_Author_removes_a_custom_document_type(t *testing.T) {
	// GIVEN a node with draft, notes, and "characters" documents.
	dir := initProject(t)
	r := addNodeJSON(t, dir, "Test Node")
	mp := getNodeMP(t, r)
	sid := getNodeSID(t, r)
	runLmkSuccess(t, dir, "types", "add", "characters", mp)

	// WHEN the author removes the "characters" document type.
	runLmkSuccess(t, dir, "types", "remove", "characters", mp)

	// THEN the node has 2 document types: draft and notes.
	stdout := runLmkSuccess(t, dir, "types", "list", mp)
	if strings.Contains(stdout, "characters") {
		t.Fatalf("characters should not appear after removal: %s", stdout)
	}

	// THEN the "characters" file is deleted.
	expectedFile := mp + "_" + sid + "_characters.md"
	if fileExists(dir, expectedFile) {
		t.Fatalf("expected characters file %s to be deleted", expectedFile)
	}
}
